import type { Metadata } from 'next';
import Link from 'next/link';
import { BreadcrumbJsonLd } from '@/components/json-ld';

export const metadata: Metadata = {
  title: 'About Our Reviews — How We Research UK Car Raffle Sites',
  description:
    'How CarRaffleOdds researches and reviews UK car competition sites — Companies House records, Trustpilot, live draw observation, and community forums. All reviews are human-written.',
  alternates: {
    canonical: '/about-our-reviews',
  },
};

const SITE_URL = 'https://www.carraffleodds.com';

export default function AboutOurReviewsPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: SITE_URL },
          { name: 'About Our Reviews', url: `${SITE_URL}/about-our-reviews` },
        ]}
      />

      <h1 className="text-3xl font-bold text-slate-900 tracking-tight mb-4">
        About Our Reviews
      </h1>
      <p className="text-lg text-slate-600 mb-10">
        How we research UK car raffle and competition sites — and what we will and won't say.
      </p>

      <div className="prose-custom space-y-8">
        <section>
          <h2>What our reviews cover</h2>
          <p>
            Each site review on CarRaffleOdds covers how the operator works, what real entrants
            say, trust signals, and — importantly — what to watch out for. We don't write
            promotional copy. If a site has concerns worth knowing about, we say so.
          </p>
          <p>
            Every review addresses: competition model (fixed-odds, Spot the Ball, or unlimited),
            ticket prices, draw schedule, free entry route, prize range, draw transparency,
            Trustpilot evidence, ownership and company registration, and responsible gambling
            provision.
          </p>
        </section>

        <section>
          <h2>How we research</h2>
          <p>We use several sources for each review:</p>
          <ul>
            <li>
              <strong>Companies House:</strong> Registered company name, number, incorporation
              date, directors, and shareholder structure. This is a public register maintained by
              the UK government — the most reliable source for legal entity information.
            </li>
            <li>
              <strong>Trustpilot:</strong> Rating and review count, positive and negative themes,
              and whether Trustpilot has flagged any account for improper review collection.
            </li>
            <li>
              <strong>The operator's own website and terms:</strong> Competition model, ticket
              limits, free entry routes, draw methodology, and responsible gambling provisions.
            </li>
            <li>
              <strong>DCMS Voluntary Code of Good Practice:</strong> Whether a site has signed
              the government's voluntary code for prize draw operators (May 2026). Signing is not
              legally binding, but it indicates a commitment to consumer protections including
              spending caps and clearer free entry routes.
            </li>
            <li>
              <strong>Community forums and press coverage:</strong> MoneySavingExpert, PistonHeads,
              Reddit, and industry press for independent perspectives on real winner experiences
              and any concerns that don't surface in official channels.
            </li>
          </ul>
        </section>

        <section>
          <h2>Who writes the reviews</h2>
          <p>
            All reviews are written by a human — not generated by AI. CarRaffleOdds is a small
            independent site, not a content farm. The prose you read on each site review page
            reflects research that has been read, assessed, and written by a person, not
            auto-produced from a template.
          </p>
          <p>
            We use AI tools to assist with research (collating Companies House data, summarising
            Trustpilot themes) but the editorial judgements — what to highlight, what to
            flag, how to describe a site fairly — are ours.
          </p>
        </section>

        <section>
          <h2>Affiliate disclosure</h2>
          <p>
            We may earn a commission when you click through from a review and purchase tickets.
            This is a standard affiliate arrangement and it does not affect what we write.
            We display the same information and cover the same concerns whether or not we have
            an affiliate relationship with a site.
          </p>
          <p>
            Listings on the{' '}
            <Link href="/sites" className="text-blue-600 hover:text-blue-700 underline">
              Sites page
            </Link>{' '}
            are sorted by year established — not by commission rate. The same principle applies
            to the main raffle comparison: we never reorder or hide listings based on whether
            we earn from a site.
          </p>
        </section>

        <section>
          <h2>What we won't do</h2>
          <ul>
            <li>Write fake urgency ("Only 3 tickets left!" or countdown resets)</li>
            <li>Misrepresent odds, prize values, or draw outcomes</li>
            <li>Conceal negative information about a site we have an affiliate deal with</li>
            <li>Rank sites by quality in a way that could be read as a guarantee or endorsement</li>
            <li>Auto-publish reviews — every page is approved by a human before it goes live</li>
          </ul>
        </section>

        <section>
          <h2>How often reviews are updated</h2>
          <p>
            We aim to update site reviews when ownership, regulatory status, or Trustpilot
            standings change significantly. Each review page carries a "Last research update"
            date at the foot. If you spot something out of date, email us at{' '}
            <a
              href="mailto:hello@carraffleodds.com"
              className="text-blue-600 hover:text-blue-700 underline"
            >
              hello@carraffleodds.com
            </a>
            .
          </p>
        </section>
      </div>
    </article>
  );
}
